# Generated by Django 5.1.3 on 2024-11-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
