# Generated by Django 5.1.3 on 2024-11-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0003_customer_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='pincode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.IntegerField(unique=True)),
                ('division_name', models.CharField(max_length=50)),
                ('region_name', models.CharField(max_length=50)),
                ('circle_name', models.CharField(max_length=50)),
                ('district_name', models.CharField(max_length=50)),
                ('state_name', models.CharField(max_length=50)),
            ],
        ),
    ]
