# Generated by Django 5.1.3 on 2024-11-21 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0006_spo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SPO',
        ),
    ]
