# Generated by Django 5.1.3 on 2024-11-21 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0007_delete_spo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPO',
            fields=[
                ('spo_id', models.AutoField(primary_key=True, serialize=False)),
                ('office_name', models.CharField(max_length=100)),
                ('divsion_name', models.CharField(max_length=50)),
                ('circle_name', models.CharField(max_length=50)),
                ('district_name', models.CharField(max_length=50)),
                ('state_name', models.CharField(max_length=50)),
                ('region_name', models.CharField(max_length=50)),
                ('telephone_number', models.IntegerField()),
                ('pincode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountpannel.pincode')),
            ],
        ),
    ]
