# Generated by Django 5.1.3 on 2024-11-21 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0008_spo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spo',
            name='telephone_number',
        ),
    ]
