# Generated by Django 5.1.3 on 2024-11-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0010_hpo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICH',
            fields=[
                ('ich_id', models.AutoField(primary_key=True, serialize=False)),
                ('ich_pincode', models.IntegerField(unique=True)),
                ('division_name', models.CharField(max_length=50)),
                ('region_name', models.CharField(max_length=50)),
                ('circle_name', models.CharField(max_length=50)),
                ('district_name', models.CharField(max_length=50)),
                ('state_name', models.CharField(max_length=50)),
                ('office_name', models.CharField(max_length=100)),
                ('hpo', models.ManyToManyField(related_name='ichs', to='accountpannel.hpo')),
            ],
        ),
        migrations.CreateModel(
            name='NSH',
            fields=[
                ('nsh_id', models.AutoField(primary_key=True, serialize=False)),
                ('nsh_pincode', models.IntegerField(unique=True)),
                ('division_name', models.CharField(max_length=50)),
                ('region_name', models.CharField(max_length=50)),
                ('circle_name', models.CharField(max_length=50)),
                ('district_name', models.CharField(max_length=50)),
                ('state_name', models.CharField(max_length=50)),
                ('office_name', models.CharField(max_length=100)),
                ('ich', models.ManyToManyField(related_name='nshs', to='accountpannel.ich')),
            ],
        ),
    ]
