# Generated by Django 5.1.3 on 2024-11-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0013_alter_parcel_consignment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignment',
            name='is_pickup',
            field=models.BooleanField(default=False),
        ),
    ]
