# Generated by Django 5.1.3 on 2024-11-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0014_consignment_is_pickup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment',
            name='created_place',
            field=models.CharField(max_length=50),
        ),
    ]
