# Generated by Django 5.1.3 on 2024-11-22 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0015_alter_consignment_created_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='senders_details',
            old_name='consigment_id',
            new_name='consignment_id',
        ),
    ]
