# Generated by Django 5.1.3 on 2024-11-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0016_rename_consigment_id_senders_details_consignment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment',
            name='created_place',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='receiver_details',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='senders_details',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
