# Generated by Django 5.1.3 on 2024-11-22 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0017_alter_consignment_created_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='consignment_id',
        ),
        migrations.RemoveField(
            model_name='consignment_qr',
            name='consignment_id',
        ),
        migrations.RemoveField(
            model_name='consignment_pickup',
            name='consignment_id',
        ),
        migrations.RemoveField(
            model_name='senders_details',
            name='consignment_id',
        ),
        migrations.DeleteModel(
            name='receiver_details',
        ),
        migrations.DeleteModel(
            name='parcel',
        ),
        migrations.DeleteModel(
            name='consignment_qr',
        ),
        migrations.DeleteModel(
            name='consignment_pickup',
        ),
        migrations.DeleteModel(
            name='consignment',
        ),
        migrations.DeleteModel(
            name='senders_details',
        ),
    ]
