# Generated by Django 5.1.3 on 2024-11-22 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0019_consignment_consignment_pickup_consignment_qr_parcel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='consignment_qr',
        ),
    ]
