# Generated by Django 5.1.3 on 2024-11-22 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0020_delete_consignment_qr'),
    ]

    operations = [
        migrations.CreateModel(
            name='consignment_qr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_url', models.URLField()),
                ('qr_url', models.URLField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50)),
                ('created_by_id', models.CharField(max_length=50)),
                ('consignment_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accountpannel.consignment')),
            ],
        ),
    ]
