# Generated by Django 5.1.3 on 2024-11-23 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0021_consignment_qr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consignment_qr',
            name='consignment_id',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='consignment_id',
        ),
        migrations.RemoveField(
            model_name='receiver_details',
            name='consignment_id',
        ),
        migrations.RemoveField(
            model_name='senders_details',
            name='consignment_id',
        ),
        migrations.CreateModel(
            name='adjacent_nsh_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(blank=True, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('traffic', models.IntegerField(blank=True, null=True)),
                ('effective_weight', models.IntegerField(blank=True, null=True)),
                ('nsh1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nsh1_relations', to='accountpannel.nsh')),
                ('nsh2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nsh2_relations', to='accountpannel.nsh')),
            ],
        ),
        migrations.DeleteModel(
            name='consignment_pickup',
        ),
        migrations.DeleteModel(
            name='consignment_qr',
        ),
        migrations.DeleteModel(
            name='parcel',
        ),
        migrations.DeleteModel(
            name='receiver_details',
        ),
        migrations.DeleteModel(
            name='consignment',
        ),
        migrations.DeleteModel(
            name='senders_details',
        ),
    ]
