# Generated by Django 5.1.3 on 2024-11-23 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0023_consignment_consignment_pickup_consignment_qr_parcel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignment',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='consignment_journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.CharField(choices=[('spo', 'spo'), ('hpo', 'hpo'), ('ich', 'ich'), ('nsh', 'nsh')], max_length=50)),
                ('created_place_id', models.IntegerField()),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('consignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountpannel.consignment')),
            ],
        ),
    ]
