# Generated by Django 5.1.3 on 2024-11-23 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0024_consignment_status_consignment_journey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='consignment_journey',
        ),
    ]
