# Generated by Django 5.1.3 on 2024-11-24 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0026_consignment_journey'),
    ]

    operations = [
        migrations.CreateModel(
            name='complains',
            fields=[
                ('complain_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('complain', models.TextField()),
                ('consignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountpannel.consignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
