# Generated by Django 5.1.3 on 2024-11-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0027_complains'),
    ]

    operations = [
        migrations.AddField(
            model_name='complains',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
