# Generated by Django 5.1.3 on 2024-11-24 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0029_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adjacent_nsh_data',
            old_name='distance',
            new_name='capacity',
        ),
        migrations.RemoveField(
            model_name='adjacent_nsh_data',
            name='effective_weight',
        ),
    ]
