# Generated by Django 5.1.3 on 2024-11-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0030_rename_distance_adjacent_nsh_data_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignment',
            name='service',
            field=models.CharField(default='Normal', max_length=50),
        ),
    ]
