# Generated by Django 5.1.3 on 2024-11-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0031_consignment_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment',
            name='service',
            field=models.CharField(choices=[('other', 'other'), ('speedpost', 'speedpost')], default='other', max_length=50),
        ),
    ]
