# Generated by Django 5.1.3 on 2024-11-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0032_alter_consignment_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment',
            name='type',
            field=models.CharField(choices=[('document', 'document'), ('parcel', 'parcel')], max_length=50),
        ),
    ]
