# Generated by Django 5.1.3 on 2024-11-25 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0034_consignment_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment_route',
            name='consignment_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accountpannel.consignment'),
        ),
    ]
