# Generated by Django 5.1.3 on 2024-11-26 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0035_alter_consignment_route_consignment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consignment_qr',
            name='created_by',
        ),
    ]
