# Generated by Django 5.1.3 on 2024-11-27 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0036_remove_consignment_qr_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='container',
            fields=[
                ('container_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50)),
                ('created_office_type', models.CharField(choices=[('spo', 'spo'), ('hpo', 'hpo'), ('ich', 'ich'), ('nsh', 'nsh')], max_length=50)),
                ('created_office_id', models.IntegerField()),
                ('consignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountpannel.consignment')),
            ],
        ),
    ]
