# Generated by Django 5.1.3 on 2024-11-27 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0037_container'),
    ]

    operations = [
        migrations.DeleteModel(
            name='container',
        ),
    ]
