# Generated by Django 5.1.3 on 2024-11-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0039_container'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='going_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
