# Generated by Django 5.1.3 on 2024-11-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0041_remove_container_consignment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment_route',
            name='route',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
