# Generated by Django 5.1.3 on 2024-11-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0042_alter_consignment_route_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment_route',
            name='route',
            field=models.TextField(blank=True, null=True),
        ),
    ]
