# Generated by Django 5.1.3 on 2024-11-28 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0043_alter_consignment_route_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='container_journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.CharField(choices=[('spo', 'spo'), ('hpo', 'hpo'), ('ich', 'ich'), ('nsh', 'nsh')], max_length=50)),
                ('created_place_id', models.IntegerField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('process', models.CharField(choices=[('check_in', 'check_in'), ('check_out', 'check_out')], max_length=10)),
                ('container_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountpannel.container')),
            ],
        ),
    ]
