# Generated by Django 5.1.3 on 2024-11-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0045_complains_is_out_for_delivery_consignment_reviews_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complains',
            name='is_out_for_delivery',
        ),
        migrations.AddField(
            model_name='consignment',
            name='is_out_for_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
