# Generated by Django 5.1.3 on 2024-12-03 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0046_remove_complains_is_out_for_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment_journey',
            name='created_at',
            field=models.CharField(choices=[('spo', 'spo'), ('hpo', 'hpo'), ('ich', 'ich'), ('nsh', 'nsh'), ('postman', 'postman')], max_length=50),
        ),
        migrations.AlterField(
            model_name='container',
            name='created_office_type',
            field=models.CharField(choices=[('spo', 'spo'), ('hpo', 'hpo'), ('ich', 'ich'), ('nsh', 'nsh'), ('postman', 'postman')], max_length=50),
        ),
        migrations.AlterField(
            model_name='container_journey',
            name='created_at',
            field=models.CharField(choices=[('spo', 'spo'), ('hpo', 'hpo'), ('ich', 'ich'), ('nsh', 'nsh'), ('postman', 'postman')], max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='type',
            field=models.CharField(choices=[('spo', 'spo'), ('hpo', 'hpo'), ('ich', 'ich'), ('nsh', 'nsh'), ('postman', 'postman')], max_length=50),
        ),
        migrations.CreateModel(
            name='otp_consignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_count', models.IntegerField(default=0)),
                ('consignment_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accountpannel.consignment')),
            ],
        ),
        migrations.CreateModel(
            name='postman_consignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postman_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountpannel.consignment')),
            ],
        ),
    ]
