# Generated by Django 5.1.3 on 2024-12-04 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0048_otp_consignments_otp_expiry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='complain_journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by_type', models.CharField(blank=True, choices=[('spo', 'spo'), ('hpo', 'hpo'), ('ich', 'ich'), ('nsh', 'nsh'), ('postman', 'postman')], max_length=50, null=True)),
                ('by_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('passed', 'passed'), ('resolved', 'resolved')], max_length=50)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('to_type', models.CharField(blank=True, choices=[('spo', 'spo'), ('hpo', 'hpo'), ('ich', 'ich'), ('nsh', 'nsh'), ('postman', 'postman')], max_length=50, null=True)),
                ('to_id', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('complain_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountpannel.complains')),
            ],
        ),
    ]
