# Generated by Django 5.1.3 on 2024-12-05 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0050_remove_complains_consignment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='complains',
            fields=[
                ('complain_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('complain', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('transferred', 'transferred'), ('resolved', 'resolved')], default='pending', max_length=20)),
                ('head_office', models.IntegerField()),
                ('current_office_type', models.CharField(choices=[('spo', 'spo'), ('hpo', 'hpo'), ('ich', 'ich'), ('nsh', 'nsh'), ('postman', 'postman')], max_length=50)),
                ('current_office_id', models.IntegerField()),
                ('consignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountpannel.consignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='complain_journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transferred_office_type', models.CharField(choices=[('spo', 'spo'), ('hpo', 'hpo'), ('ich', 'ich'), ('nsh', 'nsh'), ('postman', 'postman')], max_length=50)),
                ('transferred_office_id', models.IntegerField()),
                ('comments', models.TextField()),
                ('complain_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountpannel.complains')),
            ],
        ),
    ]
