# Generated by Django 5.1.3 on 2024-12-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0051_complains_complain_journey'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain_journey',
            name='transferred_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
