# Generated by Django 5.1.3 on 2024-12-05 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0052_complain_journey_transferred_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complains',
            old_name='head_office',
            new_name='nsh_office',
        ),
    ]
