# Generated by Django 5.1.3 on 2024-12-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0053_rename_head_office_complains_nsh_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complains',
            name='current_office_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complains',
            name='current_office_type',
            field=models.CharField(blank=True, choices=[('spo', 'spo'), ('hpo', 'hpo'), ('ich', 'ich'), ('nsh', 'nsh'), ('postman', 'postman')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='complains',
            name='nsh_office',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
