# Generated by Django 5.1.3 on 2024-12-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0054_alter_complains_current_office_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment',
            name='consignment_id',
            field=models.CharField(editable=False, max_length=12, primary_key=True, serialize=False),
        ),
    ]
