# Generated by Django 5.1.3 on 2024-12-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0056_alter_complains_complain_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complains',
            name='complain_id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='consignment_id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
