# Generated by Django 5.1.3 on 2024-12-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0057_alter_complains_complain_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignment',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consignment_route',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
