# Generated by Django 5.1.3 on 2024-12-11 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0058_consignment_time_consignment_route_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment',
            name='time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='system_complain',
            fields=[
                ('complain_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('spo', 'spo'), ('hpo', 'hpo'), ('ich', 'ich'), ('nsh', 'nsh'), ('postman', 'postman')], max_length=50)),
                ('office_id', models.IntegerField()),
                ('message', models.TextField(blank=True, null=True)),
                ('delayed_time', models.IntegerField(blank=True, null=True)),
                ('consignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountpannel.consignment')),
            ],
        ),
    ]
