# Generated by Django 5.1.3 on 2024-12-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0059_alter_consignment_time_system_complain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignment',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
