# Generated by Django 5.1.3 on 2024-12-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0060_alter_consignment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_complain',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
