# Generated by Django 5.1.3 on 2024-12-11 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0061_system_complain_created_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='system_complain',
        ),
    ]
