# Generated by Django 5.1.3 on 2024-12-11 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0062_delete_system_complain'),
    ]

    operations = [
        migrations.CreateModel(
            name='system_complain',
            fields=[
                ('complain_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('spo', 'spo'), ('hpo', 'hpo'), ('ich', 'ich'), ('nsh', 'nsh'), ('postman', 'postman')], max_length=50)),
                ('office_id', models.IntegerField()),
                ('message', models.TextField(blank=True, null=True)),
                ('delayed_time', models.IntegerField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('consignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountpannel.consignment')),
            ],
        ),
    ]
