# Generated by Django 5.1.3 on 2024-12-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0063_system_complain'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignment_journey',
            name='msg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
