# Generated by Django 5.1.3 on 2024-12-11 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0064_consignment_journey_msg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='system_complain',
        ),
    ]
