# Generated by Django 5.1.3 on 2024-12-11 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0066_system_complain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system_complain',
            old_name='delayed',
            new_name='delayed_time',
        ),
    ]
