# Generated by Django 5.1.3 on 2024-12-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0067_rename_delayed_system_complain_delayed_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_complain',
            name='delayed_time',
            field=models.CharField(blank=True, null=True),
        ),
    ]
