# Generated by Django 5.1.3 on 2024-12-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0068_alter_system_complain_delayed_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('distance', models.FloatField()),
                ('post_name', models.CharField(max_length=100)),
                ('cost', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
