# Generated by Django 5.1.3 on 2024-12-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0069_postcost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcost',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='postcost',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='postcost',
            name='post_name',
        ),
        migrations.RemoveField(
            model_name='postcost',
            name='weight',
        ),
        migrations.AddField(
            model_name='postcost',
            name='distance_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postcost',
            name='distance_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postcost',
            name='post_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='postcost',
            name='weight_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postcost',
            name='weight_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postcost',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
