# Generated by Django 5.1.3 on 2024-12-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountpannel', '0070_remove_postcost_created_at_remove_postcost_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcost',
            name='is_document',
            field=models.BooleanField(default=False),
        ),
    ]
